server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  zipkin:
    base-url: http://localhost:9411/

logging: #Defining the path of Log file's location
  file:
    name: "C:/Users/blaze/OneDrive/Desktop/microservices.log"

##We are removing this, as now we will get these common properties from CONFIG-SERVER > github application.yml file
##Congfiguration for making this EUREKA CLIENT.
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

